### ISSUE TITLE
Spanish language for pulse cms 5.1b3

### ISSUE THREAD

**Issue by wardiam** [yuzoolcode/pulsecms-languages#31]
Hi,

I have translated the english.php file to spanish language.
[spanish.zip](https://github.com/yuzoolcode/pulsecms-languages/files/1977667/spanish.zip)

Would it be posible to include it into the next pulse version, please?

Thank you very much.

Best regards,
Wardiam

**Comment by ghost** [comment]
Great thanks for this 

It's ready for next release :) 
https://github.com/yuzoolcode/pulsecms-languages/commit/85c77e9a90f90590f57aee73f2dc2f6d31e7777c
